[project]
name = "repl-nix-textrefineqt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.3",
    "pyqt6>=6.7.1",
    "requests>=2.32.3",
]
